#ifndef PROGRAMMING_PROBLEMS_CPP_P226_INVERTBINARYTREE_H
#define PROGRAMMING_PROBLEMS_CPP_P226_INVERTBINARYTREE_H
#include "util.h"

class Solution {
public:
  TreeNode* invertTree(TreeNode* root);
};

#endif //PROGRAMMING_PROBLEMS_CPP_P226_INVERTBINARYTREE_H