#ifndef PROGRAMMING_PROBLEMS_CPP_SEARCHINSERTPOSITION_H
#define PROGRAMMING_PROBLEMS_CPP_SEARCHINSERTPOSITION_H

int searchInsert(const std::vector<int>& nums, int target);

#endif //PROGRAMMING_PROBLEMS_CPP_SEARCHINSERTPOSITION_H
