#ifndef PROGRAMMING_PROBLEMS_CPP_VALIDPARENTHESES_H
#define PROGRAMMING_PROBLEMS_CPP_VALIDPARENTHESES_H
#include <string>

bool isValid(const std::string& s);

#endif //PROGRAMMING_PROBLEMS_CPP_VALIDPARENTHESES_H
